-- =============================================================================
-- JOKER RPG — SEED 001: Personagens Canônicos Iniciais
-- =============================================================================

INSERT INTO characters (
    name, 
    description, 
    rarity, 
    element, 
    class, 
    base_hp, 
    attack, 
    defense, 
    speed, 
    energy, 
    critical_chance, 
    power_rating, 
    passive_ability, 
    active_ability, 
    ultimate_ability
) VALUES 
(
    'Kage, o Lâmina Sombria',
    'Especialista em execuções rápidas e infiltração táctica nas sombras, capaz de capitalizar sobre falhas na postura inimiga.',
    'RARE',
    'DARK',
    'ASSASSIN',
    850,
    95,
    45,
    88,
    10,
    18.50,
    1280,
    '{"name": "Passo Furtivo", "description": "Aumenta a chance de esquiva em 10% quando o HP está abaixo de 50%."}'::jsonb,
    '{"name": "Golpe Espectral", "description": "Desfere um ataque rápido que ignora 20% da defesa do oponente.", "cooldown": 3, "energy_cost": 2}'::jsonb,
    '{"name": "Valsa do Eclipse", "description": "Sequência letal de cortes sombrios que causa 350 de dano e quebra 40 de postura.", "energy_cost": 5}'::jsonb
),
(
    'Ignis, o Berserker Carmesim',
    'Guerreiro consumido pelas chamas interiores que amplifica seu poder ofensivo conforme a batalha se prolonga.',
    'EPIC',
    'FIRE',
    'WARRIOR',
    1150,
    105,
    65,
    62,
    10,
    12.00,
    1450,
    '{"name": "Fúria Ardente", "description": "Ganha +5 de ataque cumulativo por 3 turnos a cada golpe desferido com sucesso."}'::jsonb,
    '{"name": "Impacto Vulcânico", "description": "Golpe esmagador com chamas que aplica o status BURN por 2 rodadas.", "cooldown": 3, "energy_cost": 3}'::jsonb,
    '{"name": "Cataclismo de Cinzas", "description": "Libera uma explosão de chamas infernais causando 420 de dano a alvos em Break.", "energy_cost": 5}'::jsonb
),
(
    'Aegis, o Bastião Telúrico',
    'Muralha viva impenetrável originária das montanhas esquecidas, focado em absorção de impacto e proteção.',
    'UNCOMMON',
    'EARTH',
    'TANK',
    1450,
    60,
    110,
    38,
    10,
    4.00,
    1190,
    '{"name": "Carapaça Pétrea", "description": "Reduz todo o dano de postura (Break) recebido em 25%."}'::jsonb,
    '{"name": "Postura Inabalável", "description": "Entra em guarda absoluta de BLOCK mitigando 60% do dano da próxima ação.", "cooldown": 2, "energy_cost": 2}'::jsonb,
    '{"name": "Ruptura Sísmica", "description": "Golpe de escudo no solo que reduz em 60 a postura do oponente e aplica STUN.", "energy_cost": 5}'::jsonb
),
(
    'Sylph, a Feiticeira do Vento',
    'Conjuradora de rajadas velozes capaz de controlar o tempo e retardar as ações adversárias.',
    'RARE',
    'WIND',
    'MAGE',
    820,
    98,
    40,
    82,
    10,
    14.00,
    1240,
    '{"name": "Fluxo dos Céus", "description": "Regenera +1 ponto de energia adicional a cada 3 rodadas de combate."}'::jsonb,
    '{"name": "Lâmina de Vácuo", "description": "Corte de ar pressurizado que causa 160 de dano com alta precisão anti-esquiva.", "cooldown": 2, "energy_cost": 2}'::jsonb,
    '{"name": "Tempestade Devastadora", "description": "Tornado cortante contínuo que esgota 50 de postura e causa 320 de dano geral.", "energy_cost": 5}'::jsonb
),
(
    'Raikou, o Imperador do Trovão',
    'Soberano guerreiro portador da eletricidade divina, domina o campo de batalha com velocidade relâmpago e pressão constante.',
    'LEGENDARY',
    'LIGHTNING',
    'WARRIOR',
    1200,
    120,
    70,
    95,
    10,
    22.00,
    1820,
    '{"name": "Sobrecarga Cinética", "description": "Golpes críticos geram +1 ponto de energia e aplicam SHOCK com 35% de chance."}'::jsonb,
    '{"name": "Investida Eletrostática", "description": "Deslocamento supersônico que atinge o alvo com 210 de dano e quebra 30 de postura.", "cooldown": 3, "energy_cost": 3}'::jsonb,
    '{"name": "Julgamento do Relâmpago Divino", "description": "Raio celestial implacável que desfere 520 de dano elemental crítico garantido.", "energy_cost": 5}'::jsonb
),
(
    'Lumina, a Sacerdotisa da Alvorada',
    'Curandeira tática dotada da luz primordial, especializada em remoção de penalidades e sustentação em duelos prolongados.',
    'UNCOMMON',
    'LIGHT',
    'SUPPORT',
    950,
    65,
    55,
    70,
    10,
    8.00,
    1120,
    '{"name": "Graça Radiante", "description": "Ao sofrer penalidades de status, há 40% de chance de dissipá-las no próximo turno."}'::jsonb,
    '{"name": "Bênção Solar", "description": "Cura 180 de HP e concede o benefício ATTACK_UP por 2 rodadas consecutivas.", "cooldown": 3, "energy_cost": 2}'::jsonb,
    '{"name": "Aurora Restauradora", "description": "Restaura 350 de HP, regenera 40 da barra de postura e dissipa todos os debuffs.", "energy_cost": 5}'::jsonb
),
(
    'Aqua, a Sentinela das Marés',
    'Guerreira equilibrada com domínio de marés defensivas, ideal para combatentes iniciantes.',
    'COMMON',
    'WATER',
    'TANK',
    1050,
    72,
    75,
    55,
    10,
    6.00,
    1050,
    '{"name": "Resiliência da Maré", "description": "Aumenta a defesa em 15% quando o Break Gauge está acima de 80%."}'::jsonb,
    '{"name": "Jato Hidráulico", "description": "Projétil aquático de alta pressão que causa 120 de dano e quebra 20 de postura.", "cooldown": 2, "energy_cost": 2}'::jsonb,
    '{"name": "Barreira do Tsunami", "description": "Gera uma barreira protetora que absorve 260 de dano no próximo turno.", "energy_cost": 4}'::jsonb
)
ON CONFLICT (name) DO NOTHING;