-- =============================================================================
-- JOKER RPG — SEED 002: Catálogo Canônico Inicial de Cartas Táticas
-- =============================================================================

INSERT INTO cards (
    name, 
    description, 
    type, 
    rarity, 
    element, 
    energy_cost, 
    damage, 
    defense, 
    break_damage, 
    effect_code, 
    cooldown, 
    requirement, 
    combo_modifier
) VALUES 
(
    'Golpe Veloz',
    'Ataque físico básico de rápida execução, ideal para iniciar sequências ofensivas.',
    'ATTACK',
    'COMMON',
    'WIND',
    1,
    80,
    0,
    15,
    'NONE',
    0,
    '{}'::jsonb,
    'COMBO_STARTER'
),
(
    'Corte Flamejante',
    'Lâmina embebida em brasas que causa dano térmico direto com moderada quebra de postura.',
    'ATTACK',
    'UNCOMMON',
    'FIRE',
    2,
    160,
    0,
    25,
    'NONE',
    0,
    '{}'::jsonb,
    'STANDARD'
),
(
    'Guarda de Ferro',
    'Postura defensiva firme que eleva consideravelmente a resistência a danos no turno adversário.',
    'DEFENSE',
    'COMMON',
    'EARTH',
    1,
    0,
    100,
    0,
    'BLOCK_STANCE',
    1,
    '{}'::jsonb,
    'DEFENSE_LINK'
),
(
    'Reflexo Eólico',
    'Movimento de evasão que eleva temporariamente as chances de esquivar totalmente do próximo golpe.',
    'DEFENSE',
    'UNCOMMON',
    'WIND',
    1,
    0,
    50,
    0,
    'DODGE_BOOST',
    1,
    '{}'::jsonb,
    'DEFENSE_LINK'
),
(
    'Postura de Riposta Sombria',
    'Prepara uma armadilha tática que reduz o dano sofrido e contra-ataca instantaneamente o agressor.',
    'DEFENSE',
    'RARE',
    'DARK',
    2,
    40,
    80,
    15,
    'COUNTER_STANCE',
    2,
    '{}'::jsonb,
    'DEFENSE_LINK'
),
(
    'Demolição de Postura',
    'Golpe pesado direcionado especificamente a desestabilizar e fraturar o Break do adversário.',
    'TECHNIQUE',
    'UNCOMMON',
    'EARTH',
    2,
    90,
    0,
    55,
    'NONE',
    1,
    '{}'::jsonb,
    'BREAK_BOOST'
),
(
    'Centelha Eletrostática',
    'Disparo elétrico instantâneo de baixo custo com chance de encadear combos velozes.',
    'ATTACK',
    'COMMON',
    'LIGHTNING',
    1,
    85,
    0,
    15,
    'NONE',
    0,
    '{}'::jsonb,
    'COMBO_LINKER'
),
(
    'Impacto Sísmico Fraturante',
    'Abandona sutilezas para gerar uma onda de choque que causa dano e desestabiliza a postura.',
    'TECHNIQUE',
    'RARE',
    'EARTH',
    3,
    150,
    0,
    70,
    'APPLY_STUN_CHANCE',
    2,
    '{}'::jsonb,
    'BREAK_FINISHER'
),
(
    'Chamas do Purgatório',
    'Incêndio contínuo e voraz que atinge o alvo e aplica o efeito queimadura (BURN).',
    'SPECIAL',
    'RARE',
    'FIRE',
    3,
    230,
    0,
    30,
    'APPLY_BURN',
    2,
    '{}'::jsonb,
    'ELEMENTAL_BURST'
),
(
    'Lança Glacial',
    'Projétil de gelo maciço perfurante que resfria a circulação de energia do alvo (FREEZE).',
    'TECHNIQUE',
    'UNCOMMON',
    'WATER',
    2,
    130,
    0,
    25,
    'APPLY_FREEZE',
    2,
    '{}'::jsonb,
    'STANDARD'
),
(
    'Barreira de Luz Sagrada',
    'Cria uma cúpula radiante que absorve até 200 de dano e protege a barra de postura contra quebras.',
    'DEFENSE',
    'RARE',
    'LIGHT',
    2,
    0,
    200,
    0,
    'APPLY_BARRIER',
    2,
    '{}'::jsonb,
    'DEFENSE_LINK'
),
(
    'Lâmina com Peçonha',
    'Corte superficial traiçoeiro que inocula toxina corrosiva cumulativa (POISON).',
    'ATTACK',
    'UNCOMMON',
    'DARK',
    1,
    75,
    0,
    10,
    'APPLY_POISON',
    1,
    '{}'::jsonb,
    'COMBO_LINKER'
),
(
    'Descarga de Alta Tensão',
    'Sobrecarga elétrica maciça que paralisa sistemas nervosos causando estado de SHOCK.',
    'SPECIAL',
    'EPIC',
    'LIGHTNING',
    4,
    320,
    0,
    50,
    'APPLY_SHOCK',
    3,
    '{}'::jsonb,
    'ELEMENTAL_BURST'
),
(
    'Fenda de Vórtice',
    'Turbilhão que desvia ataques inimigos e drena a energia tática do alvo para o usuário.',
    'TECHNIQUE',
    'EPIC',
    'WIND',
    3,
    160,
    40,
    35,
    'ENERGY_DRAIN',
    3,
    '{}'::jsonb,
    'COMBO_FINISHER'
),
(
    'Maelstrom Abissal',
    'Pressão oceânica esmagadora que debilita os atributos de ataque físico do adversário (WEAKNESS).',
    'SPECIAL',
    'EPIC',
    'WATER',
    4,
    290,
    0,
    60,
    'APPLY_WEAKNESS',
    3,
    '{}'::jsonb,
    'ELEMENTAL_BURST'
),
(
    'Julgamento da Alvorada',
    'Raio solar cósmico que purifica buffs inimigos e desfere impacto severo de luz primordial.',
    'ULTIMATE',
    'LEGENDARY',
    'LIGHT',
    5,
    490,
    0,
    75,
    'PURGE_AND_BURST',
    4,
    '{"min_combo": 2}'::jsonb,
    'ULTIMATE_EXECUTE'
),
(
    'Execução do Vazio Noturno',
    'Mergulho letal nas trevas com poder maximizado quando utilizado contra inimigos no estado BREAK.',
    'ULTIMATE',
    'LEGENDARY',
    'DARK',
    5,
    540,
    0,
    85,
    'BREAK_EXECUTION',
    4,
    '{"target_must_be_broken": false}'::jsonb,
    'ULTIMATE_EXECUTE'
),
(
    'Fúria Cataclísmica da Terra',
    'Colapso tectônico integral focado em garantir a ruptura imediata da postura defensiva do oponente.',
    'ULTIMATE',
    'EPIC',
    'EARTH',
    5,
    410,
    60,
    100,
    'GUARANTEED_BREAK',
    4,
    '{}'::jsonb,
    'ULTIMATE_EXECUTE'
)
ON CONFLICT (name) DO NOTHING;