/**
 * Joker RPG — Constantes de Domínio e Mecânicas Globais
 * Centraliza definições de regras de jogo, atributos, papéis, cálculos e restrições.
 */

const ROLES = Object.freeze({
  ADMIN_SUPREMO: 'ADMIN_SUPREMO',
  USER_NORMAL: 'USER_NORMAL'
});

const CLASSES = Object.freeze({
  ASSASSIN: 'ASSASSIN',
  WARRIOR: 'WARRIOR',
  TANK: 'TANK',
  MAGE: 'MAGE',
  SUPPORT: 'SUPPORT'
});

const ELEMENTS = Object.freeze({
  FIRE: 'FIRE',
  WATER: 'WATER',
  WIND: 'WIND',
  EARTH: 'EARTH',
  LIGHTNING: 'LIGHTNING',
  LIGHT: 'LIGHT',
  DARK: 'DARK'
});

// Matriz de Afinidades Elementais: [Atacante][Defensor] = Multiplicador
const ELEMENTAL_ADVANTAGE = Object.freeze({
  FIRE: { WATER: 0.75, WIND: 1.35, EARTH: 1.0, LIGHTNING: 1.0, LIGHT: 1.0, DARK: 1.0, FIRE: 1.0 },
  WATER: { FIRE: 1.35, EARTH: 1.35, WIND: 0.75, LIGHTNING: 0.8, LIGHT: 1.0, DARK: 1.0, WATER: 1.0 },
  WIND: { EARTH: 1.35, FIRE: 0.75, WATER: 1.2, LIGHTNING: 1.0, LIGHT: 1.0, DARK: 1.0, WIND: 1.0 },
  EARTH: { LIGHTNING: 1.35, WATER: 0.85, WIND: 0.75, FIRE: 1.0, LIGHT: 1.0, DARK: 1.0, EARTH: 1.0 },
  LIGHTNING: { WATER: 1.35, EARTH: 0.75, FIRE: 1.0, WIND: 1.0, LIGHT: 1.0, DARK: 1.0, LIGHTNING: 1.0 },
  LIGHT: { DARK: 1.35, LIGHT: 0.8, FIRE: 1.0, WATER: 1.0, WIND: 1.0, EARTH: 1.0, LIGHTNING: 1.0 },
  DARK: { LIGHT: 1.35, DARK: 0.8, FIRE: 1.0, WATER: 1.0, WIND: 1.0, EARTH: 1.0, LIGHTNING: 1.0 }
});

const RARITIES = Object.freeze({
  COMMON: 'COMMON',
  UNCOMMON: 'UNCOMMON',
  RARE: 'RARE',
  EPIC: 'EPIC',
  LEGENDARY: 'LEGENDARY',
  MYTHIC: 'MYTHIC'
});

const RARITY_MULTIPLIERS = Object.freeze({
  COMMON: 1.0,
  UNCOMMON: 1.15,
  RARE: 1.3,
  EPIC: 1.5,
  LEGENDARY: 1.75,
  MYTHIC: 2.1
});

const CARD_TYPES = Object.freeze({
  ATTACK: 'ATTACK',
  DEFENSE: 'DEFENSE',
  TECHNIQUE: 'TECHNIQUE',
  SPECIAL: 'SPECIAL',
  ULTIMATE: 'ULTIMATE'
});

const DEFENSIVE_STANCES = Object.freeze({
  NONE: 'NONE',
  BLOCK: 'BLOCK',
  DODGE: 'DODGE',
  COUNTER: 'COUNTER',
  BARRIER: 'BARRIER'
});

const STATUS_EFFECTS = Object.freeze({
  BURN: 'BURN',
  FREEZE: 'FREEZE',
  SHOCK: 'SHOCK',
  POISON: 'POISON',
  STUN: 'STUN',
  WEAKNESS: 'WEAKNESS',
  ATTACK_UP: 'ATTACK_UP',
  DEFENSE_UP: 'DEFENSE_UP'
});

const BATTLE_STATUS = Object.freeze({
  WAITING: 'WAITING',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  ABANDONED: 'ABANDONED'
});

const BATTLE_MODES = Object.freeze({
  PVE_TRAINING: 'PVE_TRAINING',
  PVP_CASUAL: 'PVP_CASUAL',
  PVP_RANKED: 'PVP_RANKED'
});

const MISSION_CATEGORIES = Object.freeze({
  DAILY: 'DAILY',
  BATTLE: 'BATTLE',
  PROGRESSION: 'PROGRESSION'
});

const MISSION_REQUIREMENTS = Object.freeze({
  WIN_BATTLES: 'WIN_BATTLES',
  PLAY_CARDS: 'PLAY_CARDS',
  EXECUTE_COMBOS: 'EXECUTE_COMBOS',
  BREAK_POSTURE: 'BREAK_POSTURE',
  USE_DEFENSE: 'USE_DEFENSE',
  DEAL_DAMAGE: 'DEAL_DAMAGE'
});

const COMBAT_RULES = Object.freeze({
  MAX_ENERGY: 10,
  STARTING_ENERGY: 3,
  ENERGY_RECOVERY_PER_TURN: 2,
  MAX_CARDS_HAND: 5,
  MAX_DECK_CARDS: 10,
  MIN_DECK_CARDS: 10,
  MAX_TURNS_PER_BATTLE: 50,
  TURN_TIME_LIMIT_SECONDS: 45,
  BASE_CRITICAL_MULTIPLIER: 1.75,
  BREAK_DAMAGE_MULTIPLIER: 1.5,
  BREAK_DURATION_TURNS: 1,
  BREAK_RECOVERY_PERCENT: 50,
  DEFAULT_BREAK_GAUGE: 100,
  DODGE_BASE_CHANCE: 0.15,
  DODGE_MAX_CHANCE: 0.65,
  BLOCK_BASE_REDUCTION: 0.4,
  COUNTER_BASE_DAMAGE_REFLECT: 0.5,
  COUNTER_BASE_DAMAGE_REDUCTION: 0.3
});

const COMBO_RULES = Object.freeze({
  MULTIPLIERS: {
    1: 1.0,
    2: 1.15,
    3: 1.3,
    4: 1.5,
    5: 1.8
  },
  MAX_COMBO_STREAK: 5
});

const UPLOAD_CONFIG = Object.freeze({
  MAX_FILE_SIZE_BYTES: 2 * 1024 * 1024, // 2MB
  ALLOWED_MIME_TYPES: ['image/jpeg', 'image/png', 'image/webp']
});

module.exports = {
  ROLES,
  CLASSES,
  ELEMENTS,
  ELEMENTAL_ADVANTAGE,
  RARITIES,
  RARITY_MULTIPLIERS,
  CARD_TYPES,
  DEFENSIVE_STANCES,
  STATUS_EFFECTS,
  BATTLE_STATUS,
  BATTLE_MODES,
  MISSION_CATEGORIES,
  MISSION_REQUIREMENTS,
  COMBAT_RULES,
  COMBO_RULES,
  UPLOAD_CONFIG
};